version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    container_name: node
    ports:
    - '9999:9999'

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app