version: '3.7'
services:
  node_app:
    build: ./gate-simulator
    ports:
      - '9999:9999'

  mysql_service:
    image: library/mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MUSQL_DATABASE=app

  postgres_service:
    image: library/postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/posgresql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app